theme: jekyll-theme-cayman
title: Welcome to EventGPS
description : A mobile app to notify users of possible traffic caused by any events along their route and suggest alternate route(s) if available.

